name: Build grok deb packages

on:
  push:
    tags:
    - "*"
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        image:
        - debian:12
        - debian:13
        host:
        - ubuntu-24.04-arm
        - ubuntu-24.04
    runs-on: ${{ matrix.host }}
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install --yes --no-install-recommends git build-essential cmake doxygen ruby libjpeg62-turbo-dev liblcms2-dev libtiff-dev libpng-dev pkgconf
        gem install fpm -v 1.17.0
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
    - name: git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: build
      id: build_deb
      run: ./build.sh
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        archive: false
        name: deb
        path: grok/build/grokj2k_*.deb
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        archive: false
        name: changes
        path: grok/build/grokj2k_*.changes
